# Default values for cloudclinic-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deployment
deployment:
  image: "nginx"
  tag: "latest"
  pullPolicy: IfNotPresent
  replicas: 1
  port: 80
  name: "nginx"

# Namespace
namespace: "default"

# Resources
resources:
  requests:
    cpu: "50m"
    memory: "50Mi"
  limits:
    memory: "100Mi"
    cpu: "1"

# Environment
environment: {}
  # uncomment name below to set environment variables to `Sandbox`.
  # Must be set to `{}` for production deployments, `Development` for development and `Staging` for staging deployments. Only for chart version: >= 1.0.6
  # name: "Sandbox"

# Tolerations
tolerations:
  enabled: true # set to `false` for production alone.

# Service
service:
  type: NodePort # NodePort, LoadBalancer, ClusterIP
  protocol:
    name: TCP
    http: 80
  annotations:
    enabled: false # Set as `true` for apis that uses internal loadbalancer with apim
    annotations: 'service.beta.kubernetes.io/azure-load-balancer-internal: "true"'

# Environment Variables sources
env:
  secret:
    # set to `true` to create a secret with the environment variables. Secret name is same with the deployment name.
    # data should contain key value pairs in the format of "key":"value".
    create: false
    data: {}
  configmap:
    # set to `true` to create a configmap with the environment variables. Configmap name is same with the deployment name.
    # data should contain key value pairs in the format of "key":"value".
    create: false
    data: {}

# autoscaling
# This is used for scaling pods horizontally.

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: nginx.cloudclinic.ng
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# persistent volume
pv:
  # uncomment below to set persistent volume
  create: false # true: create pv | false: do not create pvc
  name: "cloudclinic-pv"
  size: 8Gi
  path: "/var/lib/cloudclinic"
  storageClass: "azurefile-csi"

# volume
volume:
  bind: false # set to `true` to bind a volume. Note that `pvc.create` must be set to true for the data to be persistent.
  path: "/mnt/data" # Set to the correct path your application needs.

# persistent volume claim
pvc:
  create: false # true: create pvc | false: do not create pvc. Note that `volume.bind` must be true for this to be bond to a pod.
  name: "cloudclinic-pvc"
  size: 8Gi
  storageClass: "azurefile-csi"
